version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_ROOT_PASSWORD
      - MYSQL_DATABASE=$DATABASE
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-p$DB_ROOT_PASSWORD", "-e", "USE $DATABASE;"]
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - db:/var/lib/mysql
  
  app:
    depends_on:
      mysqldb:
        condition: service_healthy
    build: ./
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_ROOT_PASSWORD
      - DB_NAME=$DATABASE
      - DB_PORT=$DB_DOCKER_PORT
    stdin_open: true
    tty: true
volumes: 
  db: